[workspace]
members = ["blackbox-log", "fuzz"]
default-members = ["blackbox-log"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.66"

[workspace.dependencies]
blackbox-log = { version = "0.1.0", path = "blackbox-log" }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
