[package]
name = "blackbox"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
biterator = { version = "0.1.0", path = "../biterator" }
# nom = { version = "7.1.1", default-features = false, features = ["alloc"] }
num_enum = "0.5.7"
thiserror = "1.0.32"
ux = "0.1.4"

[dev-dependencies]
criterion = "0.3.6"

[profile.release]
lto = "thin"

[lib]
bench = false

[[bench]]
name = "read"
harness = false
