[package]
name = "blackbox"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"
publish = false

[workspace]
members = ["cli", "fuzz", "reference-impl", "xtask"]

[dependencies]
bitter = "0.6.0"
num_enum = "0.5.7"
thiserror = "1.0.34"
tracing = "0.1.36"

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false, features = ["cargo_bench_support", "html_reports"] }
test-case = "2.2.1"

[lib]
bench = false

[[bench]]
name = "decode"
harness = false

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
