[workspace]
members = ["blackbox-sys", "cli", "fuzz", "xtask"]
default-members = [".", "cli"]

[workspace.package]
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.64"

[workspace.dependencies]
blackbox.path = "."
bpaf = { version = "0.6.1", features = ["derive"] }
tracing = "0.1.37"

[package]
name = "blackbox"
version = "0.1.0"
publish = false

license.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
std = []
default = ["std"]

[dependencies]
bitter = "0.6.0"
memchr = "2.5.0"
num_enum = "0.5.7"
tracing.workspace = true

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
test-case = "2.2.2"

[lib]
bench = false

[[bench]]
name = "decode"
harness = false

[profile.bench]
strip = false
debug = true
debug-assertions = false

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
