[package]
name = "blackbox"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"
publish = false

[workspace]
members = ["cli", "fuzz", "reference-impl"]

[dependencies]
biterator = { version = "0.1.0", git = "https://gitlab.com/wetheredge/biterator" }
num_enum = "0.5.7"
tracing = "0.1.36"

[dev-dependencies]
criterion = { version = "0.3.6", default-features = false }
test-case = "2.2.1"

[lib]
bench = false

[[bench]]
name = "read"
harness = false

[profile.release]
lto = "thin"
