[workspace]
members = ["blackbox-log", "blackbox-log-cli", "blackbox-sys", "fuzz", "xtask"]
default-members = ["blackbox-log", "blackbox-log-cli"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.65"

[workspace.dependencies]
blackbox-log = { version = "0.1.0", path = "blackbox-log" }
bpaf = { version = "0.7.4", features = ["derive"] }

[profile.bench]
strip = false
debug = true
debug-assertions = false

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
