[package]
name = "blackbox"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"
publish = false

[workspace]
members = ["cli", "fuzz", "reference-impl", "xtask"]

[dependencies]
biterator = { version = "0.1.0", git = "https://gitlab.com/wetheredge/biterator", rev = "4a4297a" }
num_enum = "0.5.7"
tracing = "0.1.36"

[dev-dependencies]
criterion = { version = "0.3.6", default-features = false, features = ["cargo_bench_support", "html_reports"] }
test-case = "2.2.1"

[lib]
bench = false

[[bench]]
name = "read"
harness = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
