[package]
name = "blackbox"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"
publish = false

[workspace]
members = ["fuzzing", "reference-impl"]

[features]
_reference-impl = ["dep:reference-impl"]

[dependencies]
biterator = { version = "0.1.0", git = "https://gitlab.com/wetheredge/biterator" }
num_enum = "0.5.7"
reference-impl = { path = "reference-impl", optional = true }

[dev-dependencies]
criterion = { version = "0.3.6", default-features = false }

[lib]
bench = false

[[bench]]
name = "read"
harness = false

[profile.release]
lto = "thin"

[profile.fuzz]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true
