format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_try_shorthand = true
version = "Two"
wrap_comments = true