[package]
name = "xtask"
version = "0.1.0"
publish = false

edition.workspace = true
rust-version.workspace = true

[dependencies]
bpaf = { version = "0.7.6", features = ["derive"] }
serde = { version = "1.0.148", features = ["derive"] }
toml = "0.5.9"
xshell = "0.2.2"
