[package]
name = "reference-impl"
version = "0.1.0"
publish = false

license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
memfile = "0.2.1"

[build-dependencies]
cc = "1.0.73"
