[package]
name = "codegen"
version = "0.0.0"
publish = false

edition.workspace = true
license.workspace = true

[dependencies]
glob = "0.3.1"
heck = "0.4.1"
proc-macro2 = { version = "1.0.51", default-features = false }
quote = "1.0.23"
serde = { version = "^1.0.153", features = ["derive"] }
serde_yaml = "0.9.19"
syn = { version = "1.0.109", features = ["full"] }
