[package]
name = "blackbox-fuzz"
version = "0.0.0"
publish = false

license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.1.7", features = ["derive"] }
bitter = "0.6.0"
blackbox-sys = { version = "0.1.0", path = "../blackbox-sys" }
blackbox.workspace = true
libfuzzer-sys = "0.4.4"
memfile = "0.2.1"

[[bin]]
name = "file"
path = "fuzz_targets/file.rs"
test = false
bench = false
doc = false

[[bin]]
name = "variable-signed"
path = "fuzz_targets/variable_signed.rs"
test = false
bench = false
doc = false

[[bin]]
name = "variable"
path = "fuzz_targets/variable.rs"
test = false
bench = false
doc = false

[[bin]]
name = "elias-delta-signed"
path = "fuzz_targets/elias_delta_signed.rs"
test = false
bench = false
doc = false

[[bin]]
name = "elias-delta"
path = "fuzz_targets/elias_delta.rs"
test = false
bench = false
doc = false

[[bin]]
name = "tagged-variable"
path = "fuzz_targets/tagged_variable.rs"
test = false
bench = false
doc = false

[[bin]]
name = "tagged-16-v1"
path = "fuzz_targets/tagged_16_v1.rs"
test = false
bench = false
doc = false

[[bin]]
name = "tagged-16-v2"
path = "fuzz_targets/tagged_16_v2.rs"
test = false
bench = false
doc = false

[[bin]]
name = "tagged-32"
path = "fuzz_targets/tagged_32.rs"
test = false
bench = false
doc = false

[[bin]]
name = "negative-14-bit"
path = "fuzz_targets/negative_14_bit.rs"
test = false
doc = false
