root: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - xo
  - xo-typescript
  - plugin:prettier/recommended
parserOptions:
  jsx: false
  ecmaFeatures:
    jsx: false
rules:
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
  import/order:
    - warn
    - groups:
        - external
        - [parent, sibling]
        - index
        - type
      newlines-between: always
      alphabetize:
        order: asc
  import/no-cycle:
    - warn
    - ignoreExternal: true
settings:
  import/resolver:
    typescript: true
reportUnusedDisableDirectives: true
ignorePatterns:
  - dist/
