[package]
name = "blackbox-log"
version = "0.1.0"
publish = false

license.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["memchr/std", "serde/std"]
serde = ["dep:serde"]

[dependencies]
memchr = { version = "2.5.0", default-features = false }
serde = { version = "1.0.147", default-features = false, optional = true }
tracing.workspace = true

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
insta = { version = "1.21.0", default-features = false, features = ["colors", "glob", "ron"] }
test-case = "2.2.2"

[lib]
bench = false

[[bench]]
name = "decode"
harness = false
