[package]
name = "blackbox-log"
version = "0.1.0"
publish = false

license.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
std = []
default = ["std"]

[dependencies]
memchr = "2.5.0"
tracing.workspace = true

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
test-case = "2.2.2"

[lib]
bench = false

[[bench]]
name = "decode"
harness = false
