name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Build xtasks
        run: cargo build --package xtask
      - run: cargo ci check --all

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - 1.64 # MSRV
          - beta
          - nightly
        include:
          # Coverage reporting on Ubuntu with MSRV
          - os: ubuntu-latest
            toolchain: 1.64 # MSRV
            coverage: true

          # macOS & Windows only on MSRV
          - os: macos-latest
            toolchain: 1.64 # MSRV
          - os: windows-latest
            toolchain: 1.64 # MSRV

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Build xtasks
        run: cargo build --package xtask
      - name: Install nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          args: --locked
      - name: Install llvm-cov
        uses: baptiste0928/cargo-install@v1
        if: ${{ matrix.coverage }}
        with:
          crate: cargo-llvm-cov
          args: --locked

      - name: Run all tests
        run: cargo ci test

      - name: Generate coverage
        if: ${{ matrix.coverage }}
        run: cargo ci test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ matrix.coverage }}
        with:
          files: coverage.lcov

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt

      - run: cargo fmt --all --check

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
