name: CI
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.github/workflows/pages.yaml'
  pull_request:

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Install cargo-cranky
        run: cargo install --locked cargo-cranky
      - name: blackbox-log, none
        run: cargo cranky -p blackbox-log --target thumbv7em-none-eabihf --no-default-features
      - name: blackbox-log, std
        run: cargo cranky -p blackbox-log --no-default-features -F std
      - name: blackbox-log, serde
        run: cargo cranky -p blackbox-log --target thumbv7em-none-eabihf --no-default-features -F serde
      - name: blackbox-log, all
        run: cargo cranky -p blackbox-log --all-features
      - name: Workspace
        run: cargo cranky --workspace --all-targets --all-features
      - name: WebAssembly
        run: cargo cranky -p blackbox-log-wasm --target wasm32-unknown-unknown

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - msrv
          - beta
          - nightly
        include:
          - os: ubuntu-latest
            toolchain: msrv
            coverage: true
          - os: macos-latest
            toolchain: msrv
          - os: windows-latest
            toolchain: msrv

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Remove rust-toolchain file if not testing MSRV
        run: rm rust-toolchain*
        if: ${{ matrix.toolchain != 'msrv' }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        if: ${{ matrix.coverage }}

      - name: Replace symlinks with copies
        if: ${{ runner.os == 'windows' }}
        run: |
          cd blackbox-log/tests/logs
          mv fc-blackbox fc-blackbox~
          mv gimbal-ghost gimbal-ghost~
          cp -r "$(readlink fc-blackbox~)" fc-blackbox
          cp -r "$(readlink gimbal-ghost~)" gimbal-ghost
          rm -r fc-blackbox~
          rm -r gimbal-ghost~

      - name: Run tests
        run: cargo nextest run --workspace --all-features --exclude blackbox-fuzz --profile=ci

      - name: Run doctests
        run: cargo test --doc --workspace --exclude blackbox-fuzz

      - name: Generate coverage
        run: cargo llvm-cov -p blackbox-log --all-features --lcov --output-path=coverage.lcov nextest --profile=ci --run-ignored=all
        if: ${{ matrix.coverage }}

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ matrix.coverage }}
        with:
          files: coverage.lcov

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rm rust-toolchain*
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: miri
      - name: Run miri for wasm
        run: cargo +nightly miri test -p blackbox-log-wasm --target wasm32-unknown-unknown

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rm rust-toolchain*
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check rustfmt
        run: cargo +nightly fmt --all --check

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
