name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64 # MSRV
          profile: minimal
          components: clippy
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Build xtasks
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package xtask

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: ci
          args: check --all

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - 1.64 # MSRV
          - beta
          - nightly
        include:
          # Coverage reporting on Ubuntu with MSRV
          - os: ubuntu-latest
            toolchain: 1.64 # MSRV
            coverage: true

          # macOS & Windows only on MSRV
          - os: macos-latest
            toolchain: 1.64 # MSRV
          - os: windows-latest
            toolchain: 1.64 # MSRV

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: ${{ runner.os == 'Linux' }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        if: ${{ matrix.coverage }}

      - name: Build xtasks
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package xtask

      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          command: ci
          args: test

      - name: Generate coverage
        uses: actions-rs/cargo@v1
        if: ${{ matrix.coverage }}
        with:
          command: ci
          args: test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ matrix.coverage }}
        with:
          files: coverage.lcov

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64 # MSRV
          profile: minimal
          components: rustfmt
          override: true

      - name: Check rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
