name: CI
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build xtasks
        run: cargo build --package xtask
      - name: Run clippy
        run: cargo ci check --workspace

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - msrv
          - beta
          - nightly
        include:
          - os: ubuntu-latest
            toolchain: msrv
            coverage: true
          - os: macos-latest
            toolchain: msrv
          - os: windows-latest
            toolchain: msrv

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: ${{ runner.os == 'Linux' }}

      - name: Remove rust-toolchain file if not testing MSRV
        run: rm rust-toolchain*
        if: ${{ matrix.toolchain != 'msrv' }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        if: ${{ matrix.coverage }}

      - name: Build xtasks
        run: cargo build --package xtask
      - name: Run all tests
        run: cargo ci test

      - name: Generate coverage
        run: cargo ci test --coverage
        if: ${{ matrix.coverage }}

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ matrix.coverage }}
        with:
          files: coverage.lcov

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rm rust-toolchain*
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check rustfmt
        run: cargo +nightly fmt --all --check

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
