name: Devcontainer Prebuild
on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
      - .github/workflows/devcontainer.yaml
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/blackbox-log/dev-blackbox-log
          cacheFrom: ghcr.io/blackbox-log/dev-blackbox-log
