name: Devcontainer prebuild
on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
      - .github/workflows/devcontainer.yaml
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install devcontainer cli
        run: npm install -g @devcontainers/cli

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: devcontainer build --workspace-folder . --config .devcontainer/default/devcontainer.json --image-name ghcr.io/blackbox-log/blackbox-log-devcontainer --cache-from ghcr.io/blackbox-log/blackbox-log-devcontainer --push
