name: Deploy rustdoc to Pages
on:
  push:
    branches:
      - main
    paths:
      - Cargo.toml
      - 'src/**'
      - .github/workflows/pages.yaml
      - .github/workflows/pages.index.html
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Run rustdoc
        run: cargo doc --package blackbox-log --no-deps

      - name: Add redirect
        run: cp .github/workflows/pages.index.html target/doc/index.html
      - name: Disable Jekyll
        run: touch target/doc/.nojekyll
      - name: Fix permissions
        run: chmod -cR +rX ./target/doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./target/doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
